CREATE TABLE IF NOT EXISTS CUST_INFO_TB
(
	  CUST_ID	INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '고객ID'
	, CUST_NM	VARCHAR(50) NOT NULL COMMENT '고객명'
	, CUST_CD	VARCHAR(50) NOT NULL COMMENT '고객코드'
	, PIC	VARCHAR(50) NOT NULL COMMENT '담당자'
	, PHONE1	VARCHAR(13) NOT NULL COMMENT '연락처1'
	, PHONE2	VARCHAR(13) COMMENT '연락처2'
	, EMAIL_ADDR	VARCHAR(255) COMMENT '이메일'
	, WEBSITE	VARCHAR(255) COMMENT '웹사이트'
	, PAY_DT	VARCHAR(255) COMMENT '결제일'
	, DEL_YN	CHAR(1) DEFAULT 'N' COMMENT '삭제여부'
	, DEL_DT	DATETIME COMMENT '삭제일'
	, CUST_DEL_USR INT COMMENT '삭제한 사용자'	-- FK
) COMMENT '고객정보';

CREATE TABLE IF NOT EXISTS TOOL_INFO_TB
(
	  TOOL_ID	INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '툴ID'
	, SERIAL_NO	INT NOT NULL UNIQUE COMMENT '시리얼넘버'
	, CUST_ID	INT NOT NULL COMMENT '고객ID'	-- FK
	, TOOL_NO	VARCHAR(255) NOT NULL COMMENT '툴넘버'
	, MODEL_NO	VARCHAR(255) NOT NULL COMMENT '지그종류'
	, J_TYPE	VARCHAR(50) COMMENT '모델넘버'
	, J_THICKNESS	VARCHAR(50) COMMENT '지그두께'
	, J_CUTTING	VARCHAR(50) COMMENT '지그가공종류'
	, J_HOLE_CNT	INT COMMENT '지그홀개수'
	, S_TYPE	VARCHAR(50) COMMENT '제판종류'
	, S_MESH	VARCHAR(50) COMMENT '제판메쉬종류'
	, S_EMULSION	VARCHAR(50) COMMENT '제판유제종류'
	, ARRIVAL_DT	DATE COMMENT '입고일'
	, MMEMO	VARCHAR(255) COMMENT '메모'
	, JIG_OR_SS	CHAR(1) NOT NULL COMMENT ' 지그제판구분'
	, DEL_YN	CHAR(1)	NOT NULL DEFAULT 'N' COMMENT '삭제여부'
	, DEL_DT	DATETIME	COMMENT '삭제일'
	, TOOL_DEL_USR	INT COMMENT '삭제한사용자'	-- FK
) COMMENT '툴정보';


CREATE TABLE IF NOT EXISTS USR_INFO_TB
(
	  USR_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '유저ID'
	, USR_EMAIL_ADDR	VARCHAR(255) NOT NULL COMMENT '이메일'
	, USR_PW	VARCHAR(255) NOT NULL COMMENT '비밀번호'
	, USR_NM	VARCHAR(50) NOT NULL COMMENT '실명'
	, USR_NICK	VARCHAR(50) NOT NULL COMMENT '닉네임'
	, BIRTH_DT	DATE NOT NULL COMMENT '생년월일'
	, AUTH	CHAR(1) NOT NULL DEFAULT 'R' COMMENT'역할'
	, DEL_YN	CHAR(1) NOT NULL DEFAULT 'N' COMMENT '탈퇴여부'
	, DEL_DT DATETIME COMMENT '탈퇴일'
) COMMENT '사용자정보';

ALTER TABLE CUST_INFO_TB
ADD CONSTRAINT FK_CUST_DEL_USER
FOREIGN KEY(CUST_DEL_USR) REFERENCES USR_INFO_TB(USR_ID);

ALTER TABLE TOOL_INFO_TB
ADD CONSTRAINT FK_TOOL_DEL_USR
FOREIGN KEY(TOOL_DEL_USR) REFERENCES USR_INFO_TB(USR_ID);

ALTER TABLE TOOL_INFO_TB
ADD CONSTRAINT FK_CUST_ID
FOREIGN KEY(CUST_ID) REFERENCES CUST_INFO_TB(CUST_ID);

-- ALTER TABLE TOOL_INFO_TB 
-- ADD CONSTRAINT JIG_OR_SS 
-- CHECK (
-- 	(JIG_OR_SS = 'J' AND J_TYPE IS NOT NULL AND J_THICKNESS IS NOT NULL AND J_CUTTING IS NOT NULL AND J_HOLE_CNT IS NOT NULL
-- 	AND S_TYPE IS NULL AND S_MESH IS NULL AND S_EMULSION IS NULL)
-- 	OR
-- 	(JIG_OR_SS = 'S' AND J_TYPE IS NULL AND J_THICKNESS IS NULL AND J_CUTTING IS NULL AND J_HOLE_CNT IS NULL
-- 	AND S_TYPE IS NOT NULL AND S_MESH IS NOT NULL AND S_EMULSION IS NOT NULL)
-- );